#!/bin/bash

# Required args of invocation:
#        1 <emulator's receiving UDP port number in the forward (sender) direction> ,
#        2 <receiver’s network address> ,
#        3 <receiver’s receiving UDP port number> ,
#        4 <emulator's receiving UDP port number in the backward (receiver) direction> ,
#        5 <sender’s network address> ,
#        6 <sender’s receiving UDP port number> ,
#        7 <maximum delay of the link in units of millisecond> ,
#        8 <packet discard probability>
#        9 <verbose-mode> (Boolean: Set to 1, the network emulator will output its internal processing, one
#            per line, e.g. receiving Packet seqnum /ACK seqnum , discarding Packet seqnum /ACK seqnum,
#            forwarding Packet seqnum /ACK seqnum ).

# Example: $ nEmulator 9991 host2 9994 9993 host3 9992 1 0.2 0

java -cp target emulator.Emulator $1 $2 $3 $4 $5 $6 $7 $8 $9