#!/bin/bash

# Format of invocation:
#     sender <nEmulator address> <UDP port number 1> <UDP port number 2> <timeout> <filename>
# Detailed explanation of args:
#     1. <host address of the network emulator> (hostname)
#     2. <UDP port number used by the emulator to receive data from the sender>
#     3. <UDP port number used by the sender to receive ACKs from the emulator>
#     4. <timeout interval in units of millisecond>
#     5. <name of the file to be transferred> in the given order.

# Example: $ sender host1 9991 9992 50 ~/Waterloo/cs656-docs/a2/data/input/input1.txt

java -cp target sender.Sender $1 $2 $3 $4 $5